# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categoriasEmprego',
                'ordering': ('nome',),
                'verbose_name': 'categoriaEmprego',
            },
        ),
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categoriasNoticia',
                'ordering': ('nome',),
                'verbose_name': 'categoria_noticia',
            },
        ),
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('empresa', models.CharField(db_index=True, max_length=200, null=True)),
                ('contactos', models.CharField(db_index=True, max_length=300, null=True)),
                ('imagem', models.ImageField(blank=True, upload_to='Emprego/%Y/%m/%d')),
                ('disponibilidade', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_emprego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empregos', to='dundo.CategoriaEmprego')),
            ],
            options={
                'ordering': ('-criado',),
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='Eventos/%Y/%m/%d')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('fonte_noticia', models.CharField(blank=True, max_length=250, null=True)),
                ('fonte_url', models.URLField(blank=True)),
                ('noticia_texto', models.TextField(max_length=10000)),
                ('imagem_url', models.URLField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dundo_noticias', to=settings.AUTH_USER_MODEL)),
                ('categoria_noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='dundo.CategoriaNoticia')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AlterIndexTogether(
            name='emprego',
            index_together=set([('id', 'slug')]),
        ),
    ]
